django/helpdesk_deploy_old/helpdesk/api/urls.py
from django.urls import path

from .views import upload_file, get_wiki_page, upload_image, fetch_url

app_name = 'api'

urlpatterns = [
    path('UploadImage/',upload_image,name="upload_image"),
    path('UploadFile/',upload_file,name="upload_file"),
    path('FetchUrl/',fetch_url,name="fetch_url"),
    path('GetJson/',get_wiki_page,name="get_wiki_page"),
]

django/helpdesk_deploy_old/helpdesk/view/urls.py
from django.urls import path, include

from view.autch.login_logout import Login, Logout
from .dasbord import Dasbord
from .ticket_crud import TicketView, CreateTicket, TaskUpdate

app_name = 'views'

urlpatterns = [
    path('login/',Login.as_view(),name="login"),
    path('logout/',Logout.as_view(next_page='/login/'),name="logout"),
    path('newticket/',CreateTicket.as_view(),name="CreateTicket"),
    path('updateticket/<int:pk>/',TaskUpdate.as_view(),name="TaskUpdate"),
    path('ticket/<int:pk>/',TicketView.as_view(),name="detail_ticket"),
    path('<int:slug_query_pk>/<int:slug_stream_pk>/', include('view.s.urls')),
    path('', Dasbord.as_view(), name="dasbord"),
]

## /<type of vievs>/slug_query/slug_stream/ticket/<int:pk>/
    # path('ticket/<int:pk>/',DetailTask.as_view(),name="detail_ticket"),
#     path('newticket/',ContactView.as_view(),name="ContactView"),
#     # path('feed/', LatestEntriesFeed()),
#     path('kanbal/', KanbalDefault.as_view(), name="kanbal-defoult"),
#     path('kanbal/<int:slug_query_pk>/<int:slug_stream_pk>/', KanbalDefault.as_view(),name="kanbal"),
#     path('table/<int:slug_query_pk>/', Dasbord.as_view(), name="table"),
#     path('table/<int:slug_query_pk>/<int:slug_stream_pk>/', Dasbord.as_view(), name="table"),
#     path('<int:slug_query_pk>/<int:slug_stream_pk>/?/<int:pk>/', Dasbord.as_view(), name="s"),

django/helpdesk_deploy_old/helpdesk/view/templates/snippet/breadcrumbs.html
<ol class="breadcrumb">
    {% for crumb in breadcrumb_list %}
        {% if crumb.is_active %}
             <li class="active">{{ crumb.name }}</li>
        {% else  %}
            <li><a href="{{ crumb.url }}">{{ crumb.name }}</a></li>
        {% endif %}
    {% endfor %}
</ol>

django/helpdesk_deploy_old/helpdesk/view/templates/snippet/list-wraper.html
        <div class="dashboard-module">
            <div class="list-wraper-flex">
                {% for stream in stream_list %}
                <a href="{{ stream.url }}" class="list-sticker">{{ stream.name }}</a>
                {% endfor %}
            </div>
        </div>

django/helpdesk_deploy_old/helpdesk/view/templates/snippet/menu_simple.html
<nav class="navbar collapse navbar-collapse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand glyphicon glyphicon-home" href="{% url 'view:dasbord' %}">
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'view:CreateTicket' %}"><span class="glyphicon glyphicon glyphicon-record"></span> Создать
                        заявку</a></li>
                <li><a href="{% url 'wiki:wiki_dasbord' %}"><span class="glyphicon glyphicon-check"></span> Вики</a></li>
                <li><a href="{% url 'view:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Выход</a></li>
            </ul>
        </div>
 </nav>

django/helpdesk_deploy_old/helpdesk/view/templates/snippet/menu_views.html
<nav class="navbar collapse navbar-collapse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand glyphicon glyphicon-home" href="{% url 'view:dasbord' %}">
                </a>
            </div>
            <ul class="nav navbar-nav navbar-left">
                <li class="dropdown"
                    onclick='((el) => {el.classList[1] != "open" ? el.classList.add("open") : el.classList.remove("open")} )(this)'>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">{{ q_list.title }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for q in q_list.dep   %}
                            <li><a href="{{ q.url }}">{{ q.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <ul class="nav navbar-nav navbar-left">
                    <li class="dropdown"
                        onclick='((el) => {el.classList[1] != "open" ? el.classList.add("open") : el.classList.remove("open")} )(this)'>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">{{ dropdown_menu_view.title }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% for menu in dropdown_menu_view.dep  %}
                                <li><a href="{{ menu.url }}"> {{ menu.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>

                <li><a href="{% url 'view:CreateTicket' %}"><span class="glyphicon glyphicon glyphicon-record"></span> Создать
                        заявку</a></li>
                <li><a href="{% url 'wiki:wiki_dasbord' %}"><span class="glyphicon glyphicon-check"></span> Вики</a></li>
                <li><a href="{% url 'view:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Выход</a></li>
            </ul>
        </div>
 </nav>

django/helpdesk_deploy_old/helpdesk/view/templates/snippet/menu_wiki.html
<nav class="navbar collapse navbar-collapse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand glyphicon glyphicon-home" href="{% url 'view:dasbord' %}">
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'wiki:wiki_create' %}"><span class="glyphicon glyphicon glyphicon-record"></span> Создать
                        запись</a></li>
                <li><a href="{% url 'view:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Выход</a></li>
            </ul>
        </div>
 </nav>