django/helpdesk/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from django.urls import path
from . import views


urlpatterns = [
    path('unread/', views.UnreadNotificationsList.as_view(), name='unread'),
    path('mark-all-as-read/', views.mark_all_as_read, name='mark_all_as_read'),
    path('mark-as-read/<int:slug_mark>/', views.mark_as_read, name='mark_as_read'),
    path('mark-as-unread/<int:slug_notif>/', views.mark_as_unread, name='mark_as_unread'),
    path('delete/<slug:slug_notif>/', views.delete, name='delete'),
    path('api/unread_count/', views.live_unread_notification_count, name='live_unread_notification_count'),
    path('api/all_count/', views.live_all_notification_count, name='live_all_notification_count'),
    path('api/unread_list/', views.live_unread_notification_list, name='live_unread_notification_list'),
    path('api/unread_list_push/', views.live_unread_notification_list_push, name='live_unread_notification_list'),
    path('api/all_list/', views.live_all_notification_list, name='live_all_notification_list'),
    path('', views.AllNotificationsList.as_view(), name='all'),
]

app_name = 'notifications'

django/helpdesk/view/urls.py
from django.urls import path,include
from view.autch.login_logout import Login,Logout
from  .dasbord import Dasbord
from .table import Table
from .ticket_crud import TicketView,CreateTicket
import notifications.urls
from .analitic_page import admin_analitic
app_name = 'views'

urlpatterns = [
    path('login/',Login.as_view(),name="login"),
    path('logout/',Logout.as_view(next_page='/login/'),name="logout"),
    path('newticket/',CreateTicket.as_view(),name="CreateTicket"),
    path('ticket/<int:pk>/',TicketView.as_view(),name="detail_ticket"),
    path('<int:slug_query_pk>/<int:slug_sub_pk>/', Table.as_view(), name="router_table"),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('admin_analitic/',admin_analitic,name="analitic"),
    path('', Dasbord.as_view(), name="dasbord"),
]

django/helpdesk/view/templates/locations/dasbord.html
{% extends "../base.html" %}
{% load  static %}

{% block js %}
{% endblock js %}
{% block style %}
   <style>       .list-wraper-flex {
            display: flex;
        flex-wrap: wrap;
        justify-content: flex-start;
     }
        .alert-list {
            padding: 25px;
            overflow-x: hidden;
            height: 240px;
            margin-bottom: 25px;
        }

        .list-sticker {
            box-shadow: 0 0 9px -3px rgba(0, 0, 0, 0.75);
            min-width: 200px;
            height: 150px;
            background: bisque;
            margin: 10px;
            padding: 5px;
            color: coral;
            font-weight: bold;
            font-style: italic;
            word-break: break-all;
        }

        .list-sticker:hover {
            color: #23527c;
            text-decoration: none;
            background-color: aliceblue;
        }


        h2 {
            width: 100%;
            text-align: center;
            border-bottom: 1px solid #000;
            line-height: 0.1em;
            margin: 10px 0 20px;
        }

        h2 span {
            background: #fff;
            padding: 0 10px;
        }

        .box {
            padding: 25px;
        }
        .stat{
            font-size: 18px;
            }

        main{
            display: flex;
    flex-direction: column;

        }
    </style>
{% endblock style %}
{% block nav-bar %}
    {% include "snippet/menu_simple.html" %}
{% endblock nav-bar %}

    {% block body %}
<main>
    <section class="box">
        <h2> <span>Оперативная имформация</span></h2>
        <article class="col-md-4 stat ">
            <h3>Сводная статистика</h3>
            {% for data in static_data %}
            <span> </span>
                <dl class="dl-horizontal">
                    <dt>Открыто</dt>
                    <dd>{{ data.open }}</dd>
                    <dt>Переоткрыто</dt>
                    <dd>{{ data.reopen }}</dd>
                    <dt>Ваполняется</dt>
                    <dd>{{ data.work }}</dd>
                    <dt>Решена</dt>
                    <dd>{{ data.solve }}</dd>
                    <dt>Закрыто</dt>
                    <dd>{{ data.close }}</dd>
                    <dt>Ошибка</dt>
                    <dd>{{ data.err }}</dd>
                </dl>
                            {% endfor %}
        </article>
        <article class="alert-list-all col-md-8">
            <h3 class="text-center">Оповещения</h3>
            <div class="row"><a href="{% url 'notifications:mark_all_as_read' %} " class="btn-up">
            <button type="button"  class="btn btn-primary  btn-block btn-sm btn-up">Отметить как прочитанные все оповещения</button>
            </a></div>
            <div class="alert-list">
                                        {% for alert in alert_all %}
<!--               <a href="{{ alert.description }}"> <span class="col-md-12 alert alert-info" role="alert">-->
<!--                            {{ alert }}-->
<!--                </span></a>-->
                <span class="col-md-12 alert alert-info" >{{ alert }} </span>
                {% endfor %}
            </div>
        </article>
                <article>
                    {% if raiting %}
        <h3> <span>Ваша средняя оценка {{raiting}}</span></h3>
        {% endif %}

        </article>

    </section>
    <section class="box">
        <h2><span>Созданные вами заявки</span></h2>
     <table id="table" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th>Id</th>
                <th>Заголовок</th>
                <th>Тема</th>
                <th>Время последнего обновления</th>
                <th>Состояние</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% if table == None %}
            {% else %}
            {% for art in table %}
            <tr>
                <td>{{art.pk}}</td>
                <td>{{art.title}}</td>
                <td>{{art.queue}}</td>
                <td>{{art.data_create}}</td>
                <td>{{art.state}}</td>
                <td><a href="/ticket/{{art.pk}}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">перейти</a>
                </td>
            </tr>
            {% endfor %}

            {% endif %}

            </tbody>
            <tfoot>
            <tr>
                <th>Id</th>
                <th>Заголовок</th>
                <th>Тема</th>
                <th>Время последнего обновления</th>
                <th>Состояние</th>
                <th></th>
            </tr>
            </tfoot>
        </table>
            </section>
    <section class="box">
        <h2><span>Список досок</span></h2>
        <article class="list-wraper-flex">
            {% for cart in cart_all %}
            <a href="{{ cart.url }}" class="list-sticker"><article>
                <h3>{{ cart.title }}</h3>
            </article>
            </a>
            {% endfor %}
        </article>
    </section>
</main>
    {% endblock body %}

{% block extra-js %}
<!-- include javascript, jQuery FIRST -->
<script src="{% static 'vendor/jquery-3.5.1.js'%}"></script>
<script src="{% static 'vendor/jquery.dataTables.min.js'%}"></script>
<script src="{% static 'vendor/dataTables.bootstrap.min.js'%}"></script>
<script>


    var lang = {
        processing: "Подождите...",
        search: "Поиск:",
        lengthMenu: "Показать _MENU_ записей",
        info: "Записи с _START_ до _END_ из _TOTAL_ записей",
        infoEmpty: "Записи с 0 до 0 из 0 записей",
        infoFiltered: "(отфильтровано из _MAX_ записей)",
        infoPostFix: "",
        loadingRecords: "Загрузка записей...",
        zeroRecords: "Записи отсутствуют.",
        emptyTable: "В таблице отсутствуют данные",
        paginate: {
            first: "Первая",
            previous: "Предыдущая",
            next: "Следующая",
            last: "Последняя"
        },
        aria: {
            sortAscending: ": активировать для сортировки столбца по возрастанию",
            sortDescending: ": активировать для сортировки столбца по убыванию"
        },
        select: {
            rows: {
                _: "Выбрано записей: %d",
                0: "Кликните по записи для выбора",
                1: "Выбрана одна запись"
            }
        }
    }
    $(document).ready(function() {
        $('#table').DataTable({
            language:lang});
    } );
</script>

{% endblock extra-js %}

django/helpdesk/view/templates/locations/sticstic_data.html
{% extends "base.html" %}
{% load  static %}
{% load render_table from django_tables2 %}

{% block js %}

    <script src="{% static 'vendor/table/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/dataTables.searchBuilder.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/searchBuilder.bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/dataTables.dateTime.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/datetime-moment.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'vendor/table/jquery.dataTables.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/table/searchBuilder.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/table/dataTables.dateTime.min.css'%}">
    <!-- Chartjs libraries -->
    <script src="{% static 'vendor/highcharts.js'%}"></script>
    <script src="{% static 'vendor/data.js'%}"></script>
    <script src="{% static 'vendor/exporting.js'%}"></script>
    <script src="{% static 'vendor/accessibility.js'%}"></script>


{% endblock js %}
{% block style %}
{% endblock style %}

    {% block body %}
            {% render_table user_scope  "tables/template_anal.html"%}
<figure class="highcharts-figure">
    <div id="container"></div>
    <p class="highcharts-description">
    </p>
            {% render_table table_month  "tables/template_anal.html"%}
            {% render_table admin_table  "tables/template_anal.html"%}

</figure>
    {% endblock body %}
{% block extra-js %}

<script>
    Highcharts.chart('container', {
    data: {
        table: 'table-w'
    },
    chart: {
        type: 'column'
    },
    title: {
        text: 'Дата состояний заявок по дням'
    },
    yAxis: {
        allowDecimals: false,
        title: {
            text: 'Units'
        }
    },
    tooltip: {
        formatter: function () {
            return '<b>' + this.series.name + '</b><br/>' +
                this.point.y + ' ' + this.point.name.toLowerCase();
        }
    }
});
</script>
   <script src=" {% static 'vendor/table/dataTables.buttons.min.js' %}"></script>
   <script src="{% static 'vendor/table/buttons.bootstrap.min.js' %}"></script>
   <script src=" {% static 'vendor/table/jszip.min.js' %}"></script>
   <script src="{% static 'vendor/table/pdfmake.min.js' %}"></script>
   <script src="{% static 'vendor/table/vfs_fonts.js' %}"></script>
   <script src=" {% static 'vendor/table/buttons.html5.min.js' %}"></script>
  <script src=" {% static 'vendor/table/buttons.print.min.js' %}"></script>
  <script src=" {% static 'vendor/table/buttons.colVis.min.js' %}"></script>

      <script src="{% static 'vendor/table/locale_table.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/table_settings.js' %}" type="text/javascript"></script>

{% endblock extra-js %}

django/helpdesk/view/templates/locations/table.html
{% extends "../base.html" %}
{% load  static %}
{% load render_table from django_tables2 %}

{% block style %}
    <style>
        .dtsb-criteria{
            display:flex;
            }

        tr th {
            background-color: #ffa65aa8;
            font-style: oblique;
            font-family: system-ui;
            color: #888888;
        }

        .list-wraper-flex {
            display: flex;
            justify-content: start;
            overflow-x: overlay;
            padding: 25px;
        }

        .dashboard-module {
            padding: 25px;
            border: solid silver 10px;
            padding-top: 0px;
            text-align: center;
        }

        .list-sticker {
            box-shadow: 0 0 9px -3px rgba(0, 0, 0, 0.75);
            min-height: 60px;
            min-width: 200px;
            background: bisque;
            margin: 10px;
            padding: 5px;
            color: coral;
            font-weight: bold;
            font-style: italic;
            word-break: break-all;
            text-align: center;

        }

        .list-sticker:hover {
            color: #23527c;
            text-decoration: none;
            background-color: aliceblue;
        }
        .box{
            padding: 25px;
        }

        .warm{
    color:red;
    font-weight: bold;
        }
    .high{
        font-weight: bold;
        }
    .common{
    }
    .low{
    font-weight: lighter;
    }
                  ]

    </style>
{% endblock style %}
{% block js %}

    <script src="{% static 'vendor/table/moment.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/dataTables.searchBuilder.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/searchBuilder.bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/dataTables.dateTime.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/datetime-moment.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'vendor/table/jquery.dataTables.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/table/searchBuilder.bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'vendor/table/dataTables.dateTime.min.css'%}">
{% endblock js %}

 {% block body %}
    {% include "snippet/list-wraper.html" %}
        <main>
            {% render_table table_activ %}
            {% render_table table_not_activ %}
         </main>
    {% endblock body %}
{% block extra-js %}

   <script src=" {% static 'vendor/table/dataTables.buttons.min.js' %}"></script>
   <script src="{% static 'vendor/table/buttons.bootstrap.min.js' %}"></script>
   <script src=" {% static 'vendor/table/jszip.min.js' %}"></script>
   <script src="{% static 'vendor/table/pdfmake.min.js' %}"></script>
   <script src="{% static 'vendor/table/vfs_fonts.js' %}"></script>
   <script src=" {% static 'vendor/table/buttons.html5.min.js' %}"></script>
  <script src=" {% static 'vendor/table/buttons.print.min.js' %}"></script>
  <script src=" {% static 'vendor/table/buttons.colVis.min.js' %}"></script>

    <script src="{% static 'vendor/table/locale_table.js' %}" type="text/javascript"></script>
    <script src="{% static 'vendor/table/table_settings.js' %}" type="text/javascript"></script>
{% endblock extra-js %}